CREATE TABLE `election` (
  `election_id` bigint NOT NULL AUTO_INCREMENT,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` datetime(6) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `update_by` varchar(255) DEFAULT NULL,
  `updated_date` datetime(6) DEFAULT NULL,
  `election_date` date NOT NULL,
  'form_end_date' date NOT NULL,
  `election_name` varchar(255) NOT NULL,
  `result_date` date NOT NULL,
  `status` varchar(50) NOT NULL,
  `city_id` bigint NOT NULL,
  `country_id` bigint NOT NULL,
  `officer_id` bigint NOT NULL,
  `state_id` bigint NOT NULL,
  PRIMARY KEY (`election_id`),
  KEY `FKc1blxa5roq35y0ih32a4x9eiv` (`city_id`),
  KEY `FKbbe43ertsuxpv3ouvei85m5rk` (`country_id`),
  KEY `FKa04hyurhx6w4vp73wm6x4kv7u` (`officer_id`),
  KEY `FKf5nw3gi59llcblof4rybm08m6` (`state_id`),
  CONSTRAINT `FKa04hyurhx6w4vp73wm6x4kv7u` FOREIGN KEY (`officer_id`) REFERENCES `user_detail` (`id`),
  CONSTRAINT `FKbbe43ertsuxpv3ouvei85m5rk` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`),
  CONSTRAINT `FKc1blxa5roq35y0ih32a4x9eiv` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`),
  CONSTRAINT `FKf5nw3gi59llcblof4rybm08m6` FOREIGN KEY (`state_id`) REFERENCES `states` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci