CREATE TABLE `online_voting`.`user_details` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `aadhar_no` VARCHAR(45) NULL,
  `address` VARCHAR(80) NULL,
  `gender` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `created_date` DATETIME NULL,
  `update_by` VARCHAR(45) NULL,
  `update_date` DATETIME NULL,
  `isActive` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `aadhar_no_UNIQUE` (`aadhar_no` ASC) VISIBLE);
